/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UG2Vt9rqf93
 */
import { Button } from '~/components/Button'
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from '~/components/ui/select'
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardFooter,
  Card,
} from '~/components/ui/card'

export function CostCalculator() {
  return (
    <div className="bg-gray-100 p-6">
      <div className="mx-auto mt-8 max-w-7xl">
        <div className="flex justify-between">
          <div className="flex space-x-2">
            <Button variant="solid" color="blue">
              Monthly
            </Button>
            <Button variant="solid" color="white">
              Annually
              <span className="ml-2 mr-2 rounded bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800">
                Save 11%
              </span>
            </Button>
          </div>
          <div className="w-32">
            <Select>
              <SelectTrigger id="currency">
                <SelectValue placeholder="USD" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="usd">USD</SelectItem>
                <SelectItem value="eur">EUR</SelectItem>
                <SelectItem value="gbp">GBP</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="mt-10">
          <h2 className="text-3xl font-semibold">Estimate your price</h2>
          <p className="mt-2 text-lg text-gray-600">
            Calculate your expected costs for monthly test results.
          </p>
          <div className="mt-4">
            <input
              className="h-2 w-full cursor-pointer appearance-none rounded-lg bg-gray-200"
              max="300000"
              min="10000"
              type="range"
              value="100000"
            />
            <div className="mt-2 flex justify-between text-sm text-gray-600">
              <span>10k included</span>
              <span>50k</span>
              <span>100k</span>
              <span>200k</span>
              <span>300k+</span>
            </div>
          </div>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-2">
          <Card className="w-full rounded-lg border border-gray-200 bg-white p-6 dark:border-gray-800">
            <CardHeader>
              <CardTitle>Team</CardTitle>
              <CardDescription className="text-blue-600">
                $615 / month
              </CardDescription>
              <p className="mt-1 text-sm text-gray-500">
                *Save around $6,041/year on annual plan
              </p>
            </CardHeader>
            <CardFooter className="mt-6 border-t pt-4">
              <Button
                className="border-blue-600 text-blue-600"
                variant="outline"
              >
                Get Started
              </Button>
            </CardFooter>
          </Card>
          <Card className="w-full rounded-lg border border-gray-200 bg-white p-6 dark:border-gray-800">
            <CardHeader>
              <CardTitle className="text-purple-600">Business</CardTitle>
              <CardDescription className="text-purple-600">
                $750 / month
              </CardDescription>
              <p className="mt-1 text-sm text-gray-500">
                *Save around $5,351/year on annual plan
              </p>
            </CardHeader>
            <CardFooter className="mt-6 border-t pt-4">
              <Button
                className="border-purple-600 text-purple-600"
                variant="outline"
              >
                Get Started
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}
