/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UG2Vt9rqf93
 */
import { Button } from "@/components/Button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardDescription, CardHeader, CardFooter, Card } from "@/components/ui/card"

export function CostCalculator() {
  return (
    <div className="p-6 bg-gray-100">
      <div className="max-w-7xl mx-auto mt-8">
        <div className="flex justify-between">
          <div className="flex space-x-2">
            <Button variant="solid" color="blue">Monthly</Button>
            <Button variant="solid" color="white">
              Annually
              <span className="bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded ml-2">Save 11%</span>
            </Button>
          </div>
          <div className="w-32">
            <Select >
              <SelectTrigger id="currency">
                <SelectValue placeholder="USD" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="usd">USD</SelectItem>
                <SelectItem value="eur">EUR</SelectItem>
                <SelectItem value="gbp">GBP</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="mt-10">
          <h2 className="text-3xl font-semibold">Estimate your price</h2>
          <p className="text-lg text-gray-600 mt-2">Calculate your expected costs for monthly test results.</p>
          <div className="mt-4">
            <input
              className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
              max="300000"
              min="10000"
              type="range"
              value="100000"
            />
            <div className="flex justify-between text-gray-600 text-sm mt-2">
              <span>10k included</span>
              <span>50k</span>
              <span>100k</span>
              <span>200k</span>
              <span>300k+</span>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-10">
          <Card className="w-full bg-white border border-gray-200 rounded-lg p-6 dark:border-gray-800">
            <CardHeader>
              <CardTitle>Team</CardTitle>
              <CardDescription className="text-blue-600">$615 / month</CardDescription>
              <p className="text-sm text-gray-500 mt-1">*Save around $6,041/year on annual plan</p>
            </CardHeader>
            <CardFooter className="mt-6 border-t pt-4">
              <Button className="text-blue-600 border-blue-600" variant="outline">
                Get Started
              </Button>
            </CardFooter>
          </Card>
          <Card className="w-full bg-white border border-gray-200 rounded-lg p-6 dark:border-gray-800">
            <CardHeader>
              <CardTitle className="text-purple-600">Business</CardTitle>
              <CardDescription className="text-purple-600">$750 / month</CardDescription>
              <p className="text-sm text-gray-500 mt-1">*Save around $5,351/year on annual plan</p>
            </CardHeader>
            <CardFooter className="mt-6 border-t pt-4">
              <Button className="text-purple-600 border-purple-600" variant="outline">
                Get Started
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}
