/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XesX88W8jIp
 */
import { TableCell, TableRow, TableBody, Table } from '~/components/ui/table'
import { CalendarDaysIcon, CreditCardIcon, UserCircleIcon } from '@heroicons/react/20/solid'

function Foo() {
  return (
    <div className="lg:col-start-3 lg:row-end-1">
      <h2 className="sr-only">Summary</h2>
      <div className="rounded-lg bg-gray-50 shadow-sm ring-1 ring-gray-900/5">
        <dl className="flex flex-wrap">
          <div className="flex-auto pl-6 pt-6">
            <dt className="text-sm font-semibold leading-6 text-gray-900">Amount</dt>
            <dd className="mt-1 text-base font-semibold leading-6 text-gray-900">$10,560.00</dd>
          </div>
          <div className="flex-none self-end px-6 pt-4">
            <dt className="sr-only">Status</dt>
            <dd className="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
              Paid
            </dd>
          </div>
          <div className="mt-6 flex w-full flex-none gap-x-4 border-t border-gray-900/5 px-6 pt-6">
            <dt className="flex-none">
              <span className="sr-only">Client</span>
              <UserCircleIcon className="h-6 w-5 text-gray-400" aria-hidden="true" />
            </dt>
            <dd className="text-sm font-medium leading-6 text-gray-900">Alex Curren</dd>
          </div>
          <div className="mt-4 flex w-full flex-none gap-x-4 px-6">
            <dt className="flex-none">
              <span className="sr-only">Due date</span>
              <CalendarDaysIcon className="h-6 w-5 text-gray-400" aria-hidden="true" />
            </dt>
            <dd className="text-sm leading-6 text-gray-500">
              <time dateTime="2023-01-31">January 31, 2023</time>
            </dd>
          </div>
          <div className="mt-4 flex w-full flex-none gap-x-4 px-6">
            <dt className="flex-none">
              <span className="sr-only">Status</span>
              <CreditCardIcon className="h-6 w-5 text-gray-400" aria-hidden="true" />
            </dt>
            <dd className="text-sm leading-6 text-gray-500">Paid with MasterCard</dd>
          </div>
        </dl>
        <div className="mt-6 border-t border-gray-900/5 px-6 py-6">
          <a href="#" className="text-sm font-semibold leading-6 text-gray-900">
            Download receipt <span aria-hidden="true">&rarr;</span>
          </a>
        </div>
      </div>
    </div>
  )
}

export function PricingCalculator2() {
  return (
    <div className="mx-auto mt-10 max-w-4xl">
      <Foo />
      <Table className="mt-6">
        <TableBody>
          <TableRow>
            <TableCell>Number of specs</TableCell>
            <TableCell>100</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Number of tests per spec</TableCell>
            <TableCell>5</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Number of developers</TableCell>
            <TableCell>50</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Number of PR pushes per day</TableCell>
            <TableCell>10</TableCell>
          </TableRow>
          <TableRow className="bg-gray-100">
            <TableCell>Retry limit</TableCell>
            <TableCell>3</TableCell>
          </TableRow>
          <TableRow className="bg-gray-100">
            <TableCell>Number of flaky tests</TableCell>
            <TableCell>10</TableCell>
          </TableRow>
          <TableRow className="bg-gray-100">
            <TableCell>Number of failing tests</TableCell>
            <TableCell>5</TableCell>
          </TableRow>
          <TableRow className="font-bold">
            <TableCell>Number of test runs a month</TableCell>
            <TableCell>6,500,000</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Upload all failing tests and passing tests once per day</TableCell>
            <TableCell />
          </TableRow>
          <TableRow>
            <TableCell>Process on replay for each passing/failing pair</TableCell>
            <TableCell />
          </TableRow>
          <TableRow className="bg-gray-100">
            <TableCell>Number of recordings uploaded a month</TableCell>
            <TableCell>420</TableCell>
          </TableRow>
          <TableRow className="bg-gray-100">
            <TableCell>Number of recordings processed a month</TableCell>
            <TableCell>120</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Upload additional recordings</TableCell>
            <TableCell />
          </TableRow>
          <TableRow>
            <TableCell>Process additional recordings</TableCell>
            <TableCell />
          </TableRow>
          <TableRow className="bg-gray-200">
            <TableCell>Cypress plan</TableCell>
            <TableCell>$39,000</TableCell>
          </TableRow>
          <TableRow className="bg-gray-200">
            <TableCell>Team plan</TableCell>
            <TableCell>$108,360</TableCell>
          </TableRow>
          <TableRow className="bg-gray-200">
            <TableCell>Pro plan</TableCell>
            <TableCell />
          </TableRow>
        </TableBody>
      </Table>
    </div>
  )
}
